import { abarFanum } from "@/assets/fonts/abar";
import Providers from "@/components/providers";
import { Box, Paper } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import type { Metadata } from "next";
import Navbar from "@/components/sections/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="fa">
      <body className={`${abarFanum.className}`} dir="rtl">
        <AppRouterCacheProvider>
          <Providers>
            <Box
              component="main"
              sx={{
                bgcolor: "background.default",
                display: "flex",
                flexDirection: "column",
                minHeight: "100dvh",
              }}
            >
              <Navbar />
              {children}
              <Footer />
            </Box>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
